index: "public/index.html"
waitsecs: 3
server:
  port: ":8000"
  staticdir: "public"
  cachetimeoutsecs: 30
  tlsenabled: false
database: 
  protocol: "tcp"
  address: "db:3306"
  databasename: "db"
  username: "app"
  password: "app_password"

